kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:  # Configuration template for VPP in EKS
  service_prefix: 10.100.0.0/16
  vpp_dataplane_interface: eth0
  veth_mtu: "1410"
  default_ipv4_pool_cidr: 192.168.0.0/16

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_NATIVE_DRIVER
              value: "af_packet"
          resources:
            limits:
              hugepages-2Mi: 0

