kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:  # Configuration template for VPP in EKS
  service_prefix: 10.100.0.0/16
  vpp_dataplane_interface: eth0
  default_ipv4_pool_cidr: 10.10.0.0/16
  vpp_uplink_driver: af_packet
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            - name: FELIX_AWSSRCDSTCHECK
              value: Disable
            - name: IP_AUTODETECTION_METHOD
              value: interface=eth0
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_HOOK_BEFORE_VPP_RUN
              value: "echo 'sudo systemctl stop network' | chroot /host"
            - name: CALICOVPP_HOOK_VPP_RUNNING
              value: "echo 'sudo systemctl start network' | chroot /host"
            - name: CALICOVPP_HOOK_VPP_DONE_OK
              value: "echo 'sudo systemctl restart network' | chroot /host"
            - name: CALICOVPP_HOOK_VPP_ERRORED
              value: "echo 'sudo systemctl restart network' | chroot /host"
          volumeMounts:
            - mountPath: /host
              name: host-root
      volumes:
        - hostPath:
            path: /
          name: host-root
