kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:  # Configuration template for VPP in Kind
  service_prefix: 10.96.0.0/16
  vpp_dataplane_interface: eth0
  vpp_uplink_driver: af_packet
