kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  service_prefix: 10.96.0.0/12
  vpp_dataplane_interface: eth1
  veth_mtu: "1440"
  default_ipv4_pool_cidr: 172.16.0.0/16
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_NATIVE_DRIVER
              value: "af_packet"

