---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: calico-vpp-init-eks
  name: calico-vpp-init-eks
  namespace: calico-vpp-dataplane
spec:
  selector:
    matchLabels:
      k8s-app: calico-vpp-init-eks
  template:
    metadata:
      labels:
        k8s-app: calico-vpp-init-eks
    spec:
      # Run without CNI
      hostNetwork: true
      containers:
      - name: calicovpp-init-eks
        env:
        - name: HUGEPAGES
          value: "512"
        image: calicovpp/init-eks:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host-root
      volumes:
      - hostPath:
          path: /
        name: host-root
      tolerations:
        # Make sure calico-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
