kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:  # Configuration template for VPP.
  vpp_config_exec_template: |-
    create int virtio __PCI_DEVICE_ID__

  vpp_init_script: |-
    echo Y > /sys/module/vfio/parameters/enable_unsafe_noiommu_mode

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_CONFIG_EXEC_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: vpp_config_exec_template
            - name: CALICOVPP_INIT_SCRIPT_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: vpp_init_script
            - name: CALICOVPP_SWAP_DRIVER
              value: vfio-pci
            - name: CALICOVPP_VPP_STARTUP_SLEEP
              value: "5"
            - name: CALICOVPP_DEFAULT_GW
              value: "192.168.0.1"

