kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  veth_mtu: "1240"
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_DEFAULT_GW
              value: "192.168.0.1"
        - name: calico-node
          env:
            - name: CALICO_IPV4POOL_IPIP
              value: Always
